# Site settings
title: Stories and Afterwords
header-img: img/home-bg.jpg
email: sourabhrohilla@gmail.com
description: "A blog about data science, engineering and everything in between."
baseurl: ""
url: "http://www.sourabhrohilla.com"
twitter_username: sourabhrohilla
github_username:  sourabhrohilla
facebook_username:  sourabhrohilla

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
